---
# tasks file for Users
- include_vars: groups_present.yml
  tags: always

- include_vars: groups_absent.yml
  tags: always

- include_vars: users_present.yml
  tags: always

- include_vars: users_absent.yml
  tags: always

- include_vars: become_admin.yml
  tags: always

- name: Become-Admin | Make sure these groups are present
  lineinfile:
    path: /etc/sudoers
    line: '%{{item.group_name}} ALL=(ALL) NOPASSWD:ALL'
    state: "present"       
    validate: 'visudo -cf %s'
  with_items: '{{ become_admin }}'
  tags: become_admin

- name: Create-Groups | Make sure these groups are present
  group: name="{{item.name}}" system="{{item.system|default('no')}}" 
          state=present
  with_items: '{{ create_groups }}'
  tags: create_groups

- name: Delete-Groups | Make sure these groups are absent
  tags: delete_groups
  group: name="{{item.name}}" state=absent
  with_items: '{{ delete_groups }}'

- name: Create-Users | Make sure these users are present
  tags: create_users
  user: name="{{item.name}}" password="{{item.pass | password_hash('sha512')}}"
          comment="{{item.gecos|default('')}}" system="{{item.system|default('no')}}" 
          group="{{item.group|default('anonymous_group')}}"
          groups="{{','.join(item.groups)|default([])}}"
          home="{{item.home|default('/home/item.name')}}" append="{{item.append|default('yes')}}" 
          createhome="{{item.home_create|default('yes')}}" state=present
  with_items: '{{ create_users }}'

- name: Delete-Users | Make sure these users are absent
  tags: delete_users
  user: name="{{item.name}}" state=absent force="{{item.force|default('yes')}}"
  with_items: '{{ delete_users }}'
